### ISSUE TITLE
Integrate with google tag manager, possible, how?

### ISSUE THREAD

**Issue by benzkji** [jazzband/django-cookie-consent#104] opened 2023-09-11 09:29 UTC
I am currently evaluating how to implement a consent banner for a website. They use Google Tag Manager (as most or many sites nowadays). 

I found this article:
https://blog.google/products/marketingplatform/360/respect-user-consent-choices-google-tag-manager/

So the question is: As far as I understand, with django-cookie-consent it would be possible to either include or exclude the google tag manager snippet, that will thenafter include all the tags that are configured. But, reading the above article, it should be possible to always include the tag, but then tell google tag manager to not include ad related tags, but analytics would be ok, for example. 

Thinking about it, this would probably be possible with django-cookie-consent? Integrating my google tag with these APIs:
https://developers.google.com/tag-platform/tag-manager/templates/consent-apis and the consents given via django-cookie-consent? It would need to orient the consents at what google says (ad_storage/analytics_storage/security_storage, to mention a few), that's for sure.

Has anyone done this? I would be willing and motivated to write docs, as it seems it is probably a common use case, that should not prevent us from using django-cookie-consent?

**Comment by sergei-maertens** [comment] 2023-09-21 21:45
It all read a bit vague on how exactly to use it, but I think the current work being done in #99 would be a step in the direction to be able to integrate things properly via the consent initialization trigger.

I think having some reference documentation for different (analytics) providers would be incredibly valuable! I think it'd be a good thing to wait until I've published a new (beta) release though, since the rework in #99 is pretty big.

**Comment by benzkji** [comment] 2023-09-22 06:17
sounds promising, thank you. and yes, references for so commonly used analytics and tag managers would be nice, also as working examples how to do it in general.

**Comment by sergei-maertens** [comment] 2023-09-24 15:43
I've published django-cookie-consent 0.5.0b0 so the new JS functionality can be tried out. The reference documentation is on read the docs: https://django-cookie-consent.readthedocs.io/en/latest/javascript.html

It would be great if you could provide feedback on what's needed to make this work! In case you want some inspiration, I've patched on our projects with the beta: https://github.com/open-formulieren/open-forms/pull/3504 (which supports a number of analytics providers).

**Comment by drcongo** [comment] 2023-12-08 16:23
Hey @sergei-maertens - I'm testing out the JS version for you too in a Wagtail site - everything apart from accepting cookies is working. When I accept all from the banner, or accept a group from the cookie management page, it tries to set the cookie to this...

```
Set-Cookie cookie_consent=""; Domain=local.test; expires=Sat, 07 Dec 2024 16:14:51 GMT; HttpOnly; Max-Age=31536000; Path=/; SameSite=Lax
```

I'm sure I'm just missing a setting somewhere. Any ideas?

**Comment by sergei-maertens** [comment] 2023-12-08 17:33
So the issue seems to be that the `cookie_consent` value is empty?

Do you have a repository somewhere I could check out to reproduce/investigate this?

**Comment by drcongo** [comment] 2023-12-14 13:43
@sergei-maertens - Sorry for the delay in getting back to you, I think I solved it though and I think it was down to having a cookie group with no cookies in. We've now got this working with Google Tag Manager and I've got to say, it's pretty slick.

@benzkji - this is using jinja2 templates, but we ended up doing this in the templates...

```
{% if request is defined %}
    {% if not cookie_group_accepted(request, 'analytics') %}
        {% set analytics_consent = 'denied' %}
    {% else %}
        {% set analytics_consent = 'granted' %}
    {% endif %}

    {% if not cookie_group_accepted(request, 'tracking') %}
        {% set personalization_consent = 'denied' %}
    {% else %}
        {% set personalization_consent = 'granted' %}
    {% endif %}
{% endif %}

<script>
            const setDefaultConsentState = require('setDefaultConsentState');

            setDefaultConsentState({
              'ad_storage': 'denied',
              'analytics_storage': '{{ analytics_consent }}',
              'personalization_storage': '{{ personalization_consent }}',
              'wait_for_update': 500
            });
 </script>
```

Note that because it's jinja2 I've ported the template tags to Jinja template globals, for Django templates you'd just use `cookie_group_accepted` the way shown in the docs.

**Comment by sergei-maertens** [comment] 2023-12-14 13:49
Awesome and thanks for getting back to me!

**Comment by sergei-maertens** [comment] 2024-05-09 12:04
I'm going to close this issue to clean up. Any PRs to integrate specifically with GA are still welcome, but from this conversation I can't extract enough to write this documentation myself.

**Closed by sergei-maertens** 2024-05-09 12:04 UTC
Labels: question

**Comment by benzkji** [comment] 2024-12-13 15:15
After having installed django-cookie-consent, setup the new js version banner, I can say that this will probably very simple. Using @drcongo 's set or updateConsentState, after clicking accept or deny in the cookie bar (the needed event handlers are in the example code :).

As far as I can tell, @drcongo version is using the older consent integration, right?

I will try to write docs when ready!
